import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { appendLog, findTask, loadTask, saveTask } from './task.js';
import { listTrace, recordTrace, validateTrace } from './trace.js';
import { invalidatePhaseBoundary } from './phase-boundary.js';
import { assertConcurrencyMutationAuthority, yieldConcurrencyTaskReservation } from './concurrency-state.js';

export type AmendmentStatus='proposed'|'approved'|'rejected';
export interface AmendmentInput { title:string; reason:string; changes:string[]; acceptanceCriteria?:string[]; allowedFiles?:string[]; protectedFilesRemoved?:string[]; scopeAdditions?:string[]; }
export interface Amendment { schemaVersion:1|2; id:string; taskId:string; title:string; reason:string; changes:string[]; acceptanceCriteria:Array<{id:string;text:string}>; allowedFiles:string[]; protectedFilesRemoved:string[]; scopeAdditions:string[]; status:AmendmentStatus; proposedAt:string; decidedAt:string|null; decisionNote:string|null; digest:string; decisionDigest?:string|null; }
function base(root:string,id:string){return path.join(path.resolve(root),'.ai','amendments',id);}
function file(root:string,id:string,amendmentId:string){return path.join(base(root,id),`${amendmentId}.json`);}
function stable(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(',')}}`;}
function hash(value:unknown){return createHash('sha256').update(stable(value)).digest('hex');}
function nextId(root:string,id:string){return `AMD-${String(listAmendments(root,id).length+1).padStart(3,'0')}`;}
function normalizePath(value:string){const normalized=String(value).trim().replace(/\\/g,'/').replace(/^\.\//,'');if(!normalized||normalized.startsWith('/')||normalized.split('/').includes('..'))throw new Error(`Invalid amendment path: ${value}`);return normalized;}
function normalizeList(values:unknown[]|undefined){return [...new Set((values||[]).map(String).map(value=>value.trim()).filter(Boolean))];}
function immutablePart(item:Amendment){return{schemaVersion:item.schemaVersion,id:item.id,taskId:item.taskId,title:item.title,reason:item.reason,changes:item.changes,acceptanceCriteria:item.acceptanceCriteria,allowedFiles:item.allowedFiles,protectedFilesRemoved:item.protectedFilesRemoved,scopeAdditions:item.scopeAdditions,proposedAt:item.proposedAt};}
function decisionPart(item:Amendment){return{proposalDigest:item.digest,status:item.status,decidedAt:item.decidedAt,decisionNote:item.decisionNote};}
const MATERIAL_BOUNDARY_PATTERNS:Array<{label:string;rx:RegExp}>=[
  {label:'architecture',rx:/\b(?:architectural?\s+(?:change|redesign|migration)|change\s+(?:the\s+)?architecture|new\s+microservice|split\s+(?:the\s+)?service|replace\s+(?:the\s+)?framework|cambio\s+(?:de\s+)?arquitectura|rediseñ(?:o|ar)\s+(?:de\s+)?arquitectura|nuevo\s+microservicio)\b/i},
  {label:'data migration',rx:/\b(?:database\s+schema\s+change|schema\s+migration|data\s+migration|backfill|migration\s+rollback|migraci[oó]n\s+(?:de\s+)?datos|cambio\s+(?:de\s+)?esquema|rollback\s+(?:de\s+)?migraci[oó]n)\b/i},
  {label:'security/privacy',rx:/\b(?:authentication|authorization|oauth|rbac|encryption|security\s+(?:model|boundary|policy)|privacy\s+(?:model|policy)|personal\s+data|personally\s+identifiable|gdpr|autenticaci[oó]n|autorizaci[oó]n|cifrado|modelo\s+de\s+seguridad|privacidad|datos\s+personales)\b/i},
  {label:'product outcome',rx:/\b(?:new\s+user\s+flow|new\s+product\s+capability|change\s+(?:the\s+)?product\s+outcome|nuevo\s+flujo\s+de\s+usuario|nueva\s+capacidad\s+de\s+producto|cambiar\s+(?:el\s+)?resultado\s+del\s+producto)\b/i},
  {label:'risk classification',rx:/\b(?:change\s+(?:the\s+)?risk\s+(?:level|classification)|risk\s+(?:level|classification)\s+(?:to|from)|cambiar\s+(?:el\s+)?(?:nivel|clasificaci[oó]n)\s+de\s+riesgo)\b/i}
];
function amendmentBoundaryErrors(input:AmendmentInput){const text=[input.title,input.reason,...(input.changes||[]),...(input.acceptanceCriteria||[]),...(input.scopeAdditions||[])].map(String).join('\n');return MATERIAL_BOUNDARY_PATTERNS.filter(item=>item.rx.test(text)).map(item=>`Amendment crosses the bounded-change safety boundary (${item.label}); return to Product Specifier for a full specification review`);}
function legacyDecisionVerified(root:string,item:Amendment){const traceValidation=validateTrace(root,item.taskId);if(!traceValidation.valid)return false;const expected=item.status==='approved'?'specification-amendment-approved':'specification-amendment-rejected';return listTrace(root,item.taskId).some(event=>event.event===expected&&String(event.data?.amendmentId||'')===item.id&&String(event.data?.digest||'')===item.digest);}
function validateStoredAmendment(root:string,item:Amendment){if(hash(immutablePart(item))!==item.digest)throw new Error(`Amendment integrity check failed: ${item.id}`);if(item.status==='proposed'){if(item.decidedAt!==null||item.decisionNote!==null||item.decisionDigest)throw new Error(`Amendment decision integrity check failed: ${item.id}`);return;}if(!item.decidedAt)throw new Error(`Amendment decision integrity check failed: ${item.id}`);if(item.schemaVersion>=2){if(!item.decisionDigest||hash(decisionPart(item))!==item.decisionDigest)throw new Error(`Amendment decision integrity check failed: ${item.id}`);}else if(!legacyDecisionVerified(root,item))throw new Error(`Legacy amendment decision cannot be verified from trace: ${item.id}`);}
export function listAmendments(root:string,id:string):Amendment[]{const dir=base(root,id);if(!existsSync(dir))return[];return readdirSync(dir).filter(name=>name.endsWith('.json')).map(name=>{const item=JSON.parse(readFileSync(path.join(dir,name),'utf8')) as Amendment;validateStoredAmendment(root,item);return item;}).sort((a,b)=>a.id.localeCompare(b.id));}
export function pendingAmendments(root:string,id:string):Amendment[]{return listAmendments(root,id).filter(item=>item.status==='proposed');}
export function approvedAmendments(root:string,id:string):Amendment[]{return listAmendments(root,id).filter(item=>item.status==='approved');}
export function approvedAmendmentsDigest(root:string,id:string):string{return hash(approvedAmendments(root,id).map(item=>({id:item.id,digest:item.digest})));}
export function effectiveSpecificationHash(root:string,id:string,baseSpecificationHash:string):string{return hash({baseSpecificationHash,approvedAmendments:approvedAmendments(root,id).map(item=>({id:item.id,digest:item.digest}))});}
export function proposeAmendment(root:string,id:string,input:AmendmentInput,options:{sessionId?:string|null}={}):Amendment{
  assertConcurrencyMutationAuthority(root,id,options.sessionId);
  const task=loadTask(findTask(root,id));if(['done','rejected'].includes(task.meta.status))throw new Error('Closed tasks cannot receive specification amendments');if(task.meta.spec_approval!=='approved')throw new Error('Spec amendment requires an already approved base specification');
  if(!input.title?.trim()||!input.reason?.trim()||!input.changes?.length)throw new Error('Amendment title, reason, and at least one change are required');const boundaryErrors=amendmentBoundaryErrors(input);if(boundaryErrors.length)throw new Error(boundaryErrors.join('; '));
  const changes=normalizeList(input.changes),criteriaText=normalizeList(input.acceptanceCriteria),allowedFiles=normalizeList(input.allowedFiles).map(normalizePath).sort(),protectedFilesRemoved=normalizeList(input.protectedFilesRemoved).map(normalizePath).sort(),scopeAdditions=normalizeList(input.scopeAdditions);if(!changes.length)throw new Error('Amendment requires at least one non-empty change');
  const amendmentId=nextId(root,task.meta.id),acceptanceCriteria=criteriaText.map((text,index)=>({id:`AC-${amendmentId.replace('AMD-','A')}-${String(index+1).padStart(2,'0')}`,text}));
  const proposedAt=new Date().toISOString();const amendment:Amendment={schemaVersion:2,id:amendmentId,taskId:task.meta.id,title:input.title.trim(),reason:input.reason.trim(),changes,acceptanceCriteria,allowedFiles,protectedFilesRemoved,scopeAdditions,status:'proposed',proposedAt,decidedAt:null,decisionNote:null,digest:'',decisionDigest:null};amendment.digest=hash(immutablePart(amendment));mkdirSync(base(root,task.meta.id),{recursive:true});writeFileSync(file(root,task.meta.id,amendment.id),`${JSON.stringify(amendment,null,2)}\n`);task.meta.waiting_for='user';appendLog(task,`Specification amendment proposed: ${amendment.id} — ${amendment.title}. User decision required.`);const saved=saveTask(task);recordTrace(root,saved,'specification-amendment-proposed',{amendmentId:amendment.id,digest:amendment.digest,title:amendment.title});yieldConcurrencyTaskReservation(root,id,options.sessionId===undefined?{}:{sessionId:options.sessionId});return amendment;
}
export function decideAmendment(root:string,id:string,amendmentId:string,status:'approved'|'rejected',note:string):Amendment{
  const task=loadTask(findTask(root,id)),current=listAmendments(root,task.meta.id).find(item=>item.id===amendmentId);if(!current)throw new Error(`Amendment not found: ${amendmentId}`);if(current.status!=='proposed')throw new Error(`Amendment is already ${current.status}`);const target=file(root,task.meta.id,amendmentId),amendment:{[K in keyof Amendment]:Amendment[K]}={...current};
  amendment.status=status;amendment.decidedAt=new Date().toISOString();amendment.decisionNote=String(note||'').trim()||null;amendment.decisionDigest=hash(decisionPart(amendment));writeFileSync(target,`${JSON.stringify(amendment,null,2)}\n`);
  if(status==='approved'){const baseHash=String(task.meta.spec_approval_hash||'');task.meta.spec_effective_hash=effectiveSpecificationHash(root,task.meta.id,baseHash);if(task.meta.phase==='builder'||task.meta.phase==='technical-reviewer')invalidatePhaseBoundary(root,task.meta.id,task.meta.phase);appendLog(task,`Specification amendment approved: ${amendment.id}. Effective specification hash is ${task.meta.spec_effective_hash}.`);}else appendLog(task,`Specification amendment rejected: ${amendment.id}.`);
  if(!listAmendments(root,task.meta.id).some(item=>item.id!==amendment.id&&item.status==='proposed')&&task.meta.open_questions===0)task.meta.waiting_for='none';
  const saved=saveTask(task);recordTrace(root,saved,status==='approved'?'specification-amendment-approved':'specification-amendment-rejected',{amendmentId:amendment.id,digest:amendment.digest,decisionDigest:amendment.decisionDigest||'',note:amendment.decisionNote||''});return amendment;
}
export function approveAmendment(root:string,id:string,amendmentId:string,note='Approved by user'){return decideAmendment(root,id,amendmentId,'approved',note);}
export function rejectAmendment(root:string,id:string,amendmentId:string,note='Rejected by user'){return decideAmendment(root,id,amendmentId,'rejected',note);}
