import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import type { ConstitutionPrinciple } from './types.js';
function file(root:string){return path.join(path.resolve(root),'.ai','project','constitution.md');}
function dataFile(root:string){return path.join(path.resolve(root),'.ai','project','constitution.json');}
function read(root:string):ConstitutionPrinciple[]{const f=dataFile(root);if(!existsSync(f))return[];const raw=JSON.parse(readFileSync(f,'utf8')) as Array<Partial<ConstitutionPrinciple>>;return raw.map(item=>({...item,approvedBy:'user',approvalRef:String(item.approvalRef||`legacy-migration:${item.id||'unknown'}`)}) as ConstitutionPrinciple);}
function save(root:string,items:ConstitutionPrinciple[]){mkdirSync(path.dirname(dataFile(root)),{recursive:true});writeFileSync(dataFile(root),`${JSON.stringify(items,null,2)}\n`);const md=['# Project Constitution','',...items.flatMap(x=>[`## ${x.id} — ${x.title}`,'',x.statement,'',`- Status: ${x.status}`,`- Scope: ${x.scope.join(', ')}`,`- Enforcement: ${x.enforcement.kind}`,`- Command: \`${x.enforcement.command}\``,`- Approved by: ${x.approvedBy}`,`- Approval reference: ${x.approvalRef}`,''])].join('\n');writeFileSync(file(root),md);}
export function listConstitution(root:string){return read(root);}
export function addConstitutionPrinciple(root:string,input:Omit<ConstitutionPrinciple,'status'|'approvedAt'>):ConstitutionPrinciple{if(input.approvedBy!=='user'||!String(input.approvalRef||'').trim())throw new Error('Constitution principle requires explicit user approval reference');if(!/^CONST-\d{3,}$/.test(input.id))throw new Error('Constitution id must look like CONST-001');if(!input.enforcement?.command)throw new Error('Mechanical command is required');const items=read(root);if(items.some(x=>x.id===input.id))throw new Error('Constitution principle already exists');const item:ConstitutionPrinciple={...input,status:'active',approvedAt:new Date().toISOString()};items.push(item);save(root,items);return item;}
export function checkConstitution(root:string,{stage='review'}:{stage?:string}={}){const results=read(root).filter(x=>x.status==='active').map(p=>{const run=spawnSync(p.enforcement.command,{cwd:path.resolve(root),encoding:'utf8',shell:true,timeout:120000});return{id:p.id,title:p.title,command:p.enforcement.command,exitCode:run.status??1,stdout:String(run.stdout||'').slice(-4000),stderr:String(run.stderr||'').slice(-4000),ok:run.status===0};});const report={schemaVersion:1,stage,valid:results.every(x=>x.ok),results,generatedAt:new Date().toISOString()};const target=path.join(path.resolve(root),'.ai','runtime','constitution',`${stage}.json`);mkdirSync(path.dirname(target),{recursive:true});writeFileSync(target,`${JSON.stringify(report,null,2)}\n`);return{...report,path:target};}
