import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, appendFileSync, renameSync } from 'node:fs';
import path from 'node:path';
import { findTask, loadTask } from './task.js';
import { loadProjectConfig } from './project.js';
import type { EvalCandidate, FailureRecord } from './types.js';

const CATEGORIES=['wrong-target','scope-drift','visual-overflow','missing-evidence','spec-ambiguity','test-failure','architecture-violation','usability-friction','low-value','user-rejection','other'];
function normalize(s:string){return s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/task-\d+/g,'task').replace(/\d+/g,'#').replace(/[^a-z#]+/g,' ').trim().replace(/\s+/g,' ');}
function infer(statement:string,provided?:string){if(provided&&CATEGORIES.includes(provided))return provided;const s=normalize(statement);if(/overflow|desborda|sale.*texto/.test(s))return'visual-overflow';if(/captur|screenshot|section|seccion|target|objetivo/.test(s))return'wrong-target';if(/scope|alcance|fuera/.test(s))return'scope-drift';if(/test|prueba/.test(s))return'test-failure';if(/arquitect/.test(s))return'architecture-violation';if(/eviden/.test(s))return'missing-evidence';if(/valor|useful|util/.test(s))return'low-value';return provided||'other';}
function failuresFile(root:string){return path.join(path.resolve(root),'.ai','runtime','failures','failures.jsonl');}
function evalDir(root:string,status='candidates'){return path.join(path.resolve(root),'.ai','evals',status);}
export function listFailures(root:string):FailureRecord[]{const f=failuresFile(root);if(!existsSync(f))return[];return readFileSync(f,'utf8').split('\n').filter(Boolean).map(x=>JSON.parse(x));}
function candidatePath(root:string,id:string,status='candidates'){return path.join(evalDir(root,status),`${id}.md`);}
function loadCandidateFile(file:string):EvalCandidate{const raw=readFileSync(file,'utf8'),m=raw.match(/<!-- AI-FLOW:EVAL\n([\s\S]*?)\nAI-FLOW:EVAL -->/);if(!m)throw new Error(`Invalid eval candidate: ${file}`);const payload=m[1];if(payload===undefined)throw new Error(`Invalid eval candidate: ${file}`);const data=JSON.parse(payload) as EvalCandidate;return{...data,path:file};}
export function listEvalCandidates(root:string):EvalCandidate[]{const dirs=['candidates','active'],out:EvalCandidate[]=[];for(const d of dirs){const dir=evalDir(root,d);if(!existsSync(dir))continue;for(const name of readdirSync(dir))if(name.endsWith('.md'))out.push(loadCandidateFile(path.join(dir,name)));}return out;}
export function recordFailure(root:string,id:string,input:{phase?:string;category?:string;statement:string}):FailureRecord&{evalCandidateCreated:boolean;evalCandidateId:string|null}{
 const task=loadTask(findTask(root,id)),statement=String(input.statement||'').trim();if(statement.length<12)throw new Error('Failure statement must be concrete');const category=infer(statement,input.category),phase=input.phase||task.meta.phase,fingerprint=createHash('sha256').update(`${category}|${phase}|${normalize(statement)}`).digest('hex').slice(0,16),record:FailureRecord={id:`FAIL-${Date.now().toString(36)}`,taskId:task.meta.id,phase,category,statement,fingerprint,surfaces:task.meta.surfaces,at:new Date().toISOString()};
 const ff=failuresFile(root);mkdirSync(path.dirname(ff),{recursive:true});appendFileSync(ff,`${JSON.stringify(record)}\n`);const matches=listFailures(root).filter(x=>x.fingerprint===fingerprint);let evalCandidateCreated=false,evalCandidateId:null|string=null;
 const threshold=Math.max(2,Number((loadProjectConfig(root).failures as any)?.evalThreshold??2));
 if(matches.length>=threshold&&!listEvalCandidates(root).some(x=>x.fingerprint===fingerprint)){evalCandidateId=`EVAL-${fingerprint.toUpperCase()}`;const stamp=new Date().toISOString(),candidate:EvalCandidate={id:evalCandidateId,fingerprint,category,phase,statement,occurrences:matches.length,taskIds:[...new Set(matches.map(x=>x.taskId))],status:'candidate',path:candidatePath(root,evalCandidateId),createdAt:stamp,updatedAt:stamp};mkdirSync(evalDir(root),{recursive:true});const body=`# ${candidate.id} — ${category}\n\n> Generated from repeated delivery failures. Requires user approval before becoming active.\n\n## Regression intent\n\n${statement}\n\n## Given\n\nA task reaches phase \`${phase}\` with surfaces: ${task.meta.surfaces.join(', ')||'unspecified'}.\n\n## When\n\nThe workflow produces the same failure pattern.\n\n## Then\n\nThe deterministic gate or agent eval must reject it before user review.\n\n<!-- AI-FLOW:EVAL\n${JSON.stringify(candidate,null,2)}\nAI-FLOW:EVAL -->\n`;writeFileSync(candidate.path,body);evalCandidateCreated=true;}
 return{...record,evalCandidateCreated,evalCandidateId};
}
export function approveEvalCandidate(root:string,id:string,note:string):EvalCandidate{const found=listEvalCandidates(root).find(x=>x.id===id);if(!found||found.status!=='candidate')throw new Error('Eval candidate not found');const src=found.path,dst=candidatePath(root,id,'active'),updated={...found,status:'active' as const,updatedAt:new Date().toISOString(),path:dst};mkdirSync(path.dirname(dst),{recursive:true});const raw=readFileSync(src,'utf8').replace(/<!-- AI-FLOW:EVAL\n[\s\S]*?\nAI-FLOW:EVAL -->/,`<!-- AI-FLOW:EVAL\n${JSON.stringify(updated,null,2)}\nAI-FLOW:EVAL -->`).replace('Requires user approval before becoming active.',`Approved: ${note}`);writeFileSync(src,raw);renameSync(src,dst);return updated;}

export function dismissEvalCandidate(root:string,id:string,note:string):EvalCandidate{const found=listEvalCandidates(root).find(x=>x.id===id);if(!found||found.status!=='candidate')throw new Error('Eval candidate not found');const src=found.path,updated={...found,status:'dismissed' as const,updatedAt:new Date().toISOString()};const raw=readFileSync(src,'utf8').replace(/<!-- AI-FLOW:EVAL\n[\s\S]*?\nAI-FLOW:EVAL -->/,`<!-- AI-FLOW:EVAL\n${JSON.stringify(updated,null,2)}\nAI-FLOW:EVAL -->`).replace('Requires user approval before becoming active.',`Dismissed: ${note}`);writeFileSync(src,raw);return updated;}


export function applicableActiveEvals(root:string,input:{phase:string;surfaces:string[]}):EvalCandidate[]{
 const surfaces=new Set(input.surfaces);return listEvalCandidates(root).filter(candidate=>candidate.status==='active'&&candidate.phase===input.phase).filter(candidate=>{const tasks=candidate.taskIds.map(id=>{try{return loadTask(findTask(root,id));}catch{return null;}}).filter(Boolean);return tasks.length===0||tasks.some(task=>task!.meta.surfaces.length===0||task!.meta.surfaces.some(surface=>surfaces.has(surface)));});
}
