import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { approvedAmendments } from './amendments.js';
import { acceptedRevisions, activeRevision } from './revisions.js';
import { projectGovernanceHash } from './project-governance.js';
import { appendLog, findTask, getSection, loadTask, saveTask, setSection } from './task.js';

export interface BlastRadiusInput { allowedFiles:string[]; protectedFiles?:string[]; expectedSymbols?:string[]; reason:string; }
export interface BlastRadius { schemaVersion:1; taskId:string; allowedFiles:string[]; protectedFiles:string[]; expectedSymbols:string[]; reason:string; createdAt:string; digest:string; }
function file(root:string,id:string){return path.join(path.resolve(root),'.ai','scope',`${id}.json`);}
function baselineFile(root:string,id:string){return path.join(path.resolve(root),'.ai','scope',`${id}.baseline.json`);}
function hash(v:unknown){return createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function radiusPayload(radius:BlastRadius){return{schemaVersion:radius.schemaVersion,taskId:radius.taskId,allowedFiles:radius.allowedFiles,protectedFiles:radius.protectedFiles,expectedSymbols:radius.expectedSymbols,reason:radius.reason,createdAt:radius.createdAt};}
function radiusDigestValid(radius:BlastRadius){return hash(radiusPayload(radius))===radius.digest;}
function normalizeFile(v:string){const n=String(v).replace(/\\/g,'/').replace(/^\.\//,'');if(!n||n.startsWith('/')||n.split('/').includes('..'))throw new Error(`Invalid blast-radius path: ${v}`);return n;}
function globRx(pattern:string){const escaped=normalizeFile(pattern).replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*\*/g,'§§').replace(/\*/g,'[^/]*').replace(/§§/g,'.*');return new RegExp(`^${escaped}$`);}
function matches(file:string,patterns:string[]){return patterns.some(pattern=>globRx(pattern).test(file));}
function git(root:string,args:string[]){try{return execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}catch{return'';}}
function relevantFile(name:string){const n=name.replace(/\\/g,'/').replace(/^\.\//,'');return Boolean(n)&&!n.startsWith('.ai/')&&!n.startsWith('.codegraph/')&&!n.startsWith('.ai-flow-worktrees/');}
function changedFiles(root:string,baseline:string){const tracked=baseline?git(root,['diff','--name-only','--no-renames',baseline]).split(/\r?\n/).filter(Boolean):[];const untracked=git(root,['ls-files','--others','--exclude-standard']).split(/\r?\n/).filter(Boolean);return [...new Set([...tracked,...untracked].map(name=>name.replace(/\\/g,'/')).filter(relevantFile))].sort();}

const SNAPSHOT_SKIP=new Set(['.git','.ai','.codegraph','.ai-flow-worktrees','node_modules','dist','build','.next','coverage']);
function snapshot(root:string){const base=path.resolve(root),out:Record<string,string>={};function walk(dir:string,rel=''){for(const entry of readdirSync(dir,{withFileTypes:true})){if(SNAPSHOT_SKIP.has(entry.name))continue;const childRel=rel?`${rel}/${entry.name}`:entry.name,abs=path.join(dir,entry.name);if(entry.isDirectory()){walk(abs,childRel);continue;}try{const stat=lstatSync(abs),mode=(stat.mode&0o777).toString(8),key=childRel.replace(/\\/g,'/');if(stat.isSymbolicLink())out[key]=`symlink:${readlinkSync(abs)}|mode:${mode}`;else if(stat.isFile())out[key]=`${createHash('sha256').update(readFileSync(abs)).digest('hex')}|mode:${mode}`;}catch{}}}walk(base);return out;}
function writeBaselineSnapshot(root:string,id:string){const value=snapshot(root);mkdirSync(path.dirname(baselineFile(root,id)),{recursive:true});writeFileSync(baselineFile(root,id),`${JSON.stringify(value,null,2)}
`);return value;}
function snapshotChanges(baselineRoot:string,currentRoot:string,id:string){const target=baselineFile(baselineRoot,id);if(!existsSync(target))return[];const before=JSON.parse(readFileSync(target,'utf8')) as Record<string,string>,after=snapshot(currentRoot);return [...new Set([...Object.keys(before),...Object.keys(after)].filter(name=>before[name]!==after[name]).filter(relevantFile))].sort();}
function radiusSection(radius:BlastRadius){return `- Allowed files: ${radius.allowedFiles.join(', ')}\n- Protected files: ${radius.protectedFiles.join(', ')||'none'}\n- Expected symbols: ${radius.expectedSymbols.join(', ')||'none'}\n- Reason: ${radius.reason}`;}
function radiusMatchesApprovedTask(task:ReturnType<typeof loadTask>,radius:BlastRadius){return getSection(task.body,'Blast Radius').trim()===radiusSection(radius).trim();}
export function setBlastRadius(root:string,id:string,input:BlastRadiusInput):BlastRadius{const task=loadTask(findTask(root,id));if(task.meta.spec_approval==='approved')throw new Error('Approved blast radius can only change through a specification amendment');if(!input.allowedFiles?.length)throw new Error('Blast radius requires at least one allowed file or glob');const base={schemaVersion:1 as const,taskId:task.meta.id,allowedFiles:[...new Set(input.allowedFiles.map(normalizeFile))].sort(),protectedFiles:[...new Set((input.protectedFiles||[]).map(normalizeFile))].sort(),expectedSymbols:[...new Set((input.expectedSymbols||[]).map(String).map(x=>x.trim()).filter(Boolean))].sort(),reason:String(input.reason||'').trim(),createdAt:new Date().toISOString()};if(!base.reason)throw new Error('Blast radius requires a reason');const result={...base,digest:hash(base)};mkdirSync(path.dirname(file(root,id)),{recursive:true});writeFileSync(file(root,id),`${JSON.stringify(result,null,2)}\n`);task.body=setSection(task.body,'Blast Radius',radiusSection(result));task.meta.scope_guard_hash=null;task.meta.scope_baseline_commit=null;appendLog(task,`Blast radius proposed: ${result.allowedFiles.join(', ')}.`);saveTask(task);return result;}
export function loadBlastRadius(root:string,id:string):BlastRadius|null{const target=file(root,id);return existsSync(target)?JSON.parse(readFileSync(target,'utf8')) as BlastRadius:null;}
export function sealBlastRadius(root:string,id:string){const task=loadTask(findTask(root,id)),radius=loadBlastRadius(root,id);if(task.meta.route.implementation&&!radius)throw new Error('Implementation tasks require a blast radius before specification approval');if(radius){if(!radiusDigestValid(radius))throw new Error('Blast-radius artifact integrity check failed before approval');if(!radiusMatchesApprovedTask(task,radius))throw new Error('Blast-radius artifact does not match the specification section');const baseline=String(task.meta.scope_baseline_commit||'').trim(),snapshotReady=existsSync(baselineFile(root,id)),alreadySealed=task.meta.scope_guard_hash===radius.digest&&Boolean(baseline||snapshotReady);if(!alreadySealed){task.meta.scope_guard_hash=radius.digest;task.meta.scope_baseline_commit=git(root,['rev-parse','HEAD'])||null;if(!task.meta.scope_baseline_commit)writeBaselineSnapshot(root,id);appendLog(task,`Blast radius sealed with hash ${radius.digest}${task.meta.scope_baseline_commit?` at commit ${task.meta.scope_baseline_commit}`:' with a filesystem snapshot baseline'}.`);saveTask(task);}}return radius;}
export function scopeGuardStatus(root:string,id:string){
 const task=loadTask(findTask(root,id)),radius=loadBlastRadius(root,id);
 if(!task.meta.route.implementation)return{schemaVersion:2,taskId:id,applicable:false,sealed:true,sealIntegrityValid:true,valid:true,allowedFiles:[],protectedFiles:[],actualFiles:[],unexpectedFiles:[],protectedChanges:[],baselineCommit:null,governanceValid:Number(task.meta.spec_integrity_version||1)<2||task.meta.project_governance_hash===projectGovernanceHash(root),detail:'No implementation route.'};
 if(!radius)return{schemaVersion:2,taskId:id,applicable:true,sealed:false,sealIntegrityValid:false,valid:false,allowedFiles:[],protectedFiles:[],actualFiles:[],unexpectedFiles:[],protectedChanges:[],baselineCommit:task.meta.scope_baseline_commit||null,governanceValid:false,detail:'Blast radius has not been defined.'};
 const amendments=approvedAmendments(root,id),revisionScope=[...acceptedRevisions(root,id),...(activeRevision(root,id)?[activeRevision(root,id)!]:[])],allowed=[...new Set([...radius.allowedFiles,...amendments.flatMap(a=>a.allowedFiles.map(normalizeFile)),...revisionScope.flatMap(r=>r.allowedFiles.map(normalizeFile))])],removedProtected=new Set(amendments.flatMap(a=>a.protectedFilesRemoved.map(normalizeFile))),protectedFiles=radius.protectedFiles.filter(x=>!removedProtected.has(x));
 const baseline=String(task.meta.scope_baseline_commit||''),diffRoot=task.meta.worktree_path&&existsSync(task.meta.worktree_path)?task.meta.worktree_path:path.resolve(root),snapshotReady=existsSync(baselineFile(root,id));
 const actual=baseline?changedFiles(diffRoot,baseline):(snapshotReady?snapshotChanges(root,diffRoot,id):[]),unexpected=actual.filter(name=>!matches(name,allowed)),protectedChanges=actual.filter(name=>matches(name,protectedFiles));
 const digestValid=radiusDigestValid(radius),sectionValid=radiusMatchesApprovedTask(task,radius),sealIntegrityValid=Boolean(digestValid&&task.meta.scope_guard_hash&&task.meta.scope_guard_hash===radius.digest&&(baseline||snapshotReady)&&sectionValid),governanceHash=projectGovernanceHash(root),governanceValid=Number(task.meta.spec_integrity_version||1)>=2&&Boolean(task.meta.project_governance_hash)&&task.meta.project_governance_hash===governanceHash;
 const sealed=Boolean(Number(task.meta.spec_integrity_version||1)>=2&&sealIntegrityValid),valid=sealed&&governanceValid&&unexpected.length===0&&protectedChanges.length===0;
 return{schemaVersion:2,taskId:id,applicable:true,sealed,sealIntegrityValid,valid,allowedFiles:allowed,protectedFiles,expectedSymbols:radius.expectedSymbols,actualFiles:actual,unexpectedFiles:unexpected,protectedChanges,baselineCommit:baseline||null,baseDigest:radius.digest,effectiveDigest:hash({base:radius.digest,amendments:amendments.map(a=>a.digest),revisions:revisionScope.map(r=>r.digest)}),digestValid,sectionValid,governanceValid,approvedGovernanceHash:task.meta.project_governance_hash||null,currentGovernanceHash:governanceHash,detail:!digestValid?'Blast-radius artifact digest does not match its contents.':Number(task.meta.spec_integrity_version||1)<2?'Legacy approval predates the hardened Scope Guard integrity seal and must be reviewed once.':!sectionValid?'Blast-radius artifact no longer matches the approved specification section.':!sealed?'Blast radius is not sealed against the approved specification.':!governanceValid?'Governed .ai project context or policy changed after specification approval.':protectedChanges.length?`Protected file changes detected: ${protectedChanges.join(', ')}`:unexpected.length?`Changes outside approved blast radius: ${unexpected.join(', ')}`:'Actual changes stay inside the approved blast radius and governed .ai context is unchanged.'};
}
