import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { initProject } from '../dist/src/lib/project.js';
import { createTask, findTask, loadTask, saveTask, setSection } from '../dist/src/lib/task.js';
import { startRefinement, completePhase, approveSpecification } from '../dist/src/lib/workflow.js';
import { readyProjectContext } from './helpers.mjs';
import { setBlastRadius } from '../dist/src/lib/scope-guard.js';
import { createReplay,startReplayVariant,completeReplayVariant,compareReplay,recordReplayEvent } from '../dist/src/lib/replay.js';
import { recommendHarness } from '../dist/src/lib/policy.js';

function root(){const r=mkdtempSync(path.join(tmpdir(),'specrail-rh-'));git(r,['init','-b','main']);git(r,['config','user.email','test@example.com']);git(r,['config','user.name','SpecRail Test']);writeFileSync(path.join(r,'app.txt'),'base\n');git(r,['add','.']);git(r,['commit','-m','base']);return r;}
function git(r,args){return execFileSync('git',args,{cwd:r,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function task(r,{type='feature',surfaces=['backend'],risk='medium',size='medium'}={}){initProject(r,{name:'Replay'});readyProjectContext(r);const t=createTask(r,{title:`Replay ${type} contract`,type,surfaces,risk,size});startRefinement(r,t.meta.id);const d=loadTask(findTask(r,t.meta.id));d.body=setSection(d.body,'Need','Deliver one deterministic contract for replay evaluation.');d.body=setSection(d.body,'Product Value','Measure harness behavior against identical requirements.');d.body=setSection(d.body,'Users','Developers evaluating delivery quality.');d.body=setSection(d.body,'Scope','Implement only the specified observable behavior.');d.body=setSection(d.body,'Out of Scope','Unrelated refactors and deployment changes.');d.body=setSection(d.body,'Acceptance Criteria','- GET /health returns HTTP 200.\n- Response contains status ok.');d.body=setSection(d.body,'Gherkin','Scenario: health\nGiven healthy\nWhen GET /health\nThen HTTP 200');d.body=setSection(d.body,'QA Mission','Persona: developer\nStarting point: running service\nGoal: verify health\nAllowed interface: HTTP API\nSuccess: returns 200 and status ok\nFailure: contract differs');d.body=setSection(d.body,'Implementation Plan','1. Implement minimal change.\n2. Verify it.');if(surfaces.some(x=>['frontend','ui','ux'].includes(x)))d.body=setSection(d.body,'UI Target','Route: /\nTarget: main\nCapture: focused-section\nViewport: 390x844');saveTask(d);if(d.meta.route.implementation)setBlastRadius(r,t.meta.id,{allowedFiles:['app.txt'],reason:'Replay implementation boundary.'});completePhase(r,t.meta.id);approveSpecification(r,t.meta.id,'approved');return t.meta.id;}
function usageFile(worktree,usage){writeFileSync(path.join(worktree,'usage.json'),JSON.stringify(usage));return 'usage.json';}
function finish(r,replay,variant,{repairs=0,model='same',active=0}={}){const s=startReplayVariant(r,replay.id,variant),base=Date.parse(s.startedAt)+1;let tick=0;const at=(offset=0)=>new Date(base+offset).toISOString();recordReplayEvent(r,replay.id,variant,{kind:'agent-active-start',at:at(tick++)});for(let i=0;i<repairs;i++)recordReplayEvent(r,replay.id,variant,{kind:'repair-attempt',at:at(tick++)});recordReplayEvent(r,replay.id,variant,{kind:'context-file',file:'app.txt',at:at(tick++)});recordReplayEvent(r,replay.id,variant,{kind:'tool-call',tool:'test',at:at(tick++)});recordReplayEvent(r,replay.id,variant,{kind:'agent-active-stop',at:at(active*1000+tick)});writeFileSync(path.join(s.worktreePath,'proof.txt'),'proof\n');const usage={source:'usage-export',scope:'variant-total',model,inputTokens:1000,cachedInputTokens:200,outputTokens:200};usage.artifactPath=usageFile(s.worktreePath,usage);return completeReplayVariant(r,replay.id,variant,{outcome:'accepted',tasksetDigest:s.tasksetDigest,harnessDigest:s.harnessDigest,qaMissionHash:replay.taskset.qaMissionHash,verification:{acceptance:'pass',qaMission:'pass'},evidence:[{kind:'proof',path:'proof.txt'}],metrics:{repairAttempts:99,contextFiles:99,contextExpansions:99,toolCalls:99,tokenUsage:usage}});}

test('incomplete replay has no winner and running variants are not historical samples',()=>{const r=root(),id=task(r),replay=createReplay(r,id,['fast','standard']);finish(r,replay,'fast');startReplayVariant(r,replay.id,'standard');const c=compareReplay(r,replay.id);assert.equal(c.complete,false);assert.equal(c.winner,null);assert.equal(c.decisionStatus,'provisional');const rec=recommendHarness(r,id);assert.equal(rec.status,'insufficient-data');assert.equal(rec.profiles.fast.samples,0);});

test('token usage requires provenance artifact matching the reported values',()=>{const r=root(),id=task(r),replay=createReplay(r,id,['fast','standard']);const s=startReplayVariant(r,replay.id,'fast');writeFileSync(path.join(s.worktreePath,'proof.txt'),'proof');writeFileSync(path.join(s.worktreePath,'usage.json'),JSON.stringify({source:'usage-export',scope:'variant-total',model:'same',inputTokens:999,cachedInputTokens:200,outputTokens:200}));assert.throws(()=>completeReplayVariant(r,replay.id,'fast',{outcome:'accepted',tasksetDigest:s.tasksetDigest,harnessDigest:s.harnessDigest,qaMissionHash:replay.taskset.qaMissionHash,verification:{acceptance:'pass',qaMission:'pass'},evidence:[{kind:'proof',path:'proof.txt'}],metrics:{tokenUsage:{source:'usage-export',scope:'variant-total',model:'same',inputTokens:1000,cachedInputTokens:200,outputTokens:200,artifactPath:'usage.json'}}}),/token provenance|usage artifact/i);});

test('replay derives work metrics from its trace and separates wall clock from active-agent time',()=>{const r=root(),id=task(r),replay=createReplay(r,id,['fast','standard']);finish(r,replay,'fast',{repairs:2,active:12});finish(r,replay,'standard',{repairs:0,active:5});const c=compareReplay(r,replay.id),fast=c.rows.find(x=>x.variant==='fast');assert.equal(fast.repairAttempts,2);assert.equal(fast.contextFiles,1);assert.equal(fast.toolCalls,1);assert.equal(fast.activeAgentSeconds,12);assert.ok(fast.wallClockSeconds>=0);assert.equal(fast.metricsSource,'replay-trace');});

test('replay rejects unbalanced active-agent intervals and makes the failed variant terminal',()=>{const r=root(),id=task(r),replay=createReplay(r,id,['fast','standard']),s=startReplayVariant(r,replay.id,'fast');recordReplayEvent(r,replay.id,'fast',{kind:'agent-active-start'});writeFileSync(path.join(s.worktreePath,'proof.txt'),'proof');assert.throws(()=>completeReplayVariant(r,replay.id,'fast',{outcome:'accepted',tasksetDigest:s.tasksetDigest,harnessDigest:s.harnessDigest,qaMissionHash:replay.taskset.qaMissionHash,verification:{acceptance:'pass',qaMission:'pass'},evidence:[{kind:'proof',path:'proof.txt'}]}),/unclosed agent-active interval/i);assert.equal(compareReplay(r,replay.id).rows.find(x=>x.variant==='fast').status,'failed');assert.throws(()=>startReplayVariant(r,replay.id,'fast'),/can only start once/i);});

test('replay token provenance cannot escape the worktree through a symlink',()=>{const r=root(),id=task(r),replay=createReplay(r,id,['fast','standard']),s=startReplayVariant(r,replay.id,'fast'),outside=path.join(r,'outside-usage.json');writeFileSync(outside,JSON.stringify({source:'usage-export',scope:'variant-total',model:'same',inputTokens:1000,cachedInputTokens:200,outputTokens:200}));symlinkSync(outside,path.join(s.worktreePath,'usage-link.json'));writeFileSync(path.join(s.worktreePath,'proof.txt'),'proof');assert.throws(()=>completeReplayVariant(r,replay.id,'fast',{outcome:'accepted',tasksetDigest:s.tasksetDigest,harnessDigest:s.harnessDigest,qaMissionHash:replay.taskset.qaMissionHash,verification:{acceptance:'pass',qaMission:'pass'},evidence:[{kind:'proof',path:'proof.txt'}],metrics:{tokenUsage:{source:'usage-export',scope:'variant-total',model:'same',inputTokens:1000,cachedInputTokens:200,outputTokens:200,artifactPath:'usage-link.json'}}}),/resolves outside the variant worktree/i);});

test('semantic cohorts do not mix same-risk work with materially different task routes',()=>{const r=root(),ordinary=task(r,{type:'task',surfaces:['backend'],risk:'low',size:'small'});for(let i=0;i<3;i++){const rep=createReplay(r,ordinary,['fast','standard']);finish(r,rep,'fast');finish(r,rep,'standard');}const database=createTask(r,{title:'Database contract redesign',type:'database',surfaces:['backend'],risk:'low',size:'small'});const rec=recommendHarness(r,database.meta.id);assert.equal(rec.status,'insufficient-data');assert.equal(rec.cohort.sampledReplays,0);});
