import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmodSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync, execFileSync } from 'node:child_process';
import { loadWorkerResult, workerUsageRecord } from '../dist/src/lib/worker-results.js';

function stable(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;}
function digest(value){return createHash('sha256').update(stable(value)).digest('hex');}
function git(root,args){return execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function repo(){const root=mkdtempSync(path.join(tmpdir(),'specrail-worker-'));git(root,['init','-b','main']);git(root,['config','user.email','test@example.com']);git(root,['config','user.name','SpecRail Test']);writeFileSync(path.join(root,'app.txt'),'base\n');writeFileSync(path.join(root,'other.txt'),'base\n');git(root,['add','.']);git(root,['commit','-m','base']);return root;}
function fakeCodex(root){const file=path.join(root,'fake-codex.mjs');writeFileSync(file,`#!/usr/bin/env node\nimport { writeFileSync } from 'node:fs';\nimport path from 'node:path';\nconst args=process.argv.slice(2),i=args.indexOf('--model'),model=i>=0?args[i+1]:'';\nif(process.env.FAKE_MODE==='unavailable-luna'&&model==='gpt-5.6-luna'){console.error('unknown model gpt-5.6-luna');process.exit(5);}\nif(process.env.FAKE_MODE==='ordinary-failure'){console.error('tests failed normally');process.exit(7);}\nif(process.env.FAKE_MODE==='mutate-production')writeFileSync(path.join(process.cwd(),'app.txt'),'worker changed\\n');\nif(process.env.FAKE_MODE==='mutate-other')writeFileSync(path.join(process.cwd(),'other.txt'),'worker changed\\n');\nconsole.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'STATUS: COMPLETED\\nCHANGED: fake\\nVALIDATED: fake\\nESCALATION: none',model},usage:{input_tokens:100,cached_input_tokens:20,output_tokens:10}}));\n`);chmodSync(file,0o755);return file;}
function workerOrder(root,{models=['gpt-5.6-luna','gpt-5.6-terra'],mutationAuthority='specrail-state-only',allowedFiles=[],protectedFiles=[]}={}){const base={schemaVersion:2,id:'WO-ABCDEF123456',taskId:'TASK-0001',phase:mutationAuthority==='production-with-scope'?'builder':'qa-engineer',actor:mutationAuthority==='production-with-scope'?'ai-flow-builder':'ai-flow-qa-engineer',action:'continue',recommendedSkill:mutationAuthority==='production-with-scope'?'ai-flow-builder':'ai-flow-qa-engineer',kind:mutationAuthority==='production-with-scope'?'implementation':'verification',requestedModels:models,reasoningEffort:'low',access:'workspace-write',mutationAuthority,cwd:root,authority:{specificationHash:null,qaMissionHash:null,scopeGuardHash:null,decisions:''},capsule:{goal:'validate',scope:'',outOfScope:'',acceptanceCriteria:'',allowedFiles,protectedFiles,contextFiles:[],contextSymbols:[],stopIf:['material decision']},sourceDigest:'source',createdAt:new Date(0).toISOString()};const order={...base,orderDigest:digest(base)},file=path.join(root,'order.json');writeFileSync(file,`${JSON.stringify(order,null,2)}\n`);return file;}
function run(root,mode,options={}){const order=workerOrder(root,options),fake=fakeCodex(root),processResult=spawnSync(process.execPath,['scripts/specrail-worker.mjs','--order',order,'--host','codex'],{cwd:process.cwd(),encoding:'utf8',env:{...process.env,SPEC_RAIL_CODEX_BIN:fake,FAKE_MODE:mode||''}});let payload=null;try{payload=JSON.parse(processResult.stdout);}catch{}return{process:processResult,payload,order};}

test('state-only worker ignores unchanged pre-existing dirty production files',()=>{const root=repo();writeFileSync(path.join(root,'app.txt'),'already dirty\n');const r=run(root,'');assert.equal(r.process.status,0,r.process.stderr);assert.deepEqual(r.payload.result.changedFiles,[]);assert.deepEqual(r.payload.result.forbiddenProductionChanges,[]);});

test('state-only worker fails when it actually mutates production code',()=>{const r=run(repo(),'mutate-production');assert.equal(r.process.status,2);assert.equal(r.payload.result.status,'failed');assert.deepEqual(r.payload.result.forbiddenProductionChanges,['app.txt']);assert.match(r.payload.result.summary,/WORKER_MUTATION_AUTHORITY_VIOLATION/);});

test('Builder worker permits sealed allowed files and blocks outside/protected scope',()=>{const ok=run(repo(),'mutate-production',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.equal(ok.process.status,0,ok.process.stderr);assert.deepEqual(ok.payload.result.unexpectedScopeChanges,[]);const bad=run(repo(),'mutate-other',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.equal(bad.process.status,2);assert.deepEqual(bad.payload.result.unexpectedScopeChanges,['other.txt']);});

test('worker falls back Luna to Terra only when Luna is unavailable',()=>{const r=run(repo(),'unavailable-luna');assert.equal(r.process.status,0,r.process.stderr);assert.deepEqual(r.payload.result.attempts.map(x=>x.model),['gpt-5.6-luna','gpt-5.6-terra']);assert.equal(r.payload.result.requestedModel,'gpt-5.6-terra');assert.equal(r.payload.result.brainModelFallbackUsed,false);});

test('ordinary Luna failure does not retry Terra or Brain',()=>{const r=run(repo(),'ordinary-failure');assert.equal(r.process.status,7);assert.deepEqual(r.payload.result.attempts.map(x=>x.model),['gpt-5.6-luna']);assert.equal(r.payload.result.brainModelFallbackUsed,false);});

test('Brain-side loader validates result binding/model attestation and converts usage safely',()=>{const r=run(repo(),'');assert.equal(r.process.status,0,r.process.stderr);const loaded=loadWorkerResult(r.payload.resultFile,r.order);assert.equal(loaded.result.status,'completed');assert.equal(loaded.result.effectiveModel,'gpt-5.6-luna');assert.equal(loaded.result.modelAttested,true);const usage=workerUsageRecord(loaded.result,loaded.order);assert.equal(usage.owner,'worker');assert.equal(usage.model,'gpt-5.6-luna');assert.equal(usage.modelAttested,true);assert.equal(usage.inputTokens,100);assert.equal(usage.cachedInputTokens,20);assert.equal(usage.outputTokens,10);});
