import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync, execFileSync } from 'node:child_process';
import { loadWorkerResult, workerUsageRecord } from '../dist/src/lib/worker-results.js';

function stable(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;}
function digest(value){return createHash('sha256').update(stable(value)).digest('hex');}
function git(root,args){return execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}
function repo(){const root=mkdtempSync(path.join(tmpdir(),'specrail-worker-'));git(root,['init','-b','main']);git(root,['config','user.email','test@example.com']);git(root,['config','user.name','SpecRail Test']);writeFileSync(path.join(root,'app.txt'),'base\n');writeFileSync(path.join(root,'other.txt'),'base\n');git(root,['add','.']);git(root,['commit','-m','base']);return root;}
function fakeCodex(root){const file=path.join(root,'fake-codex.mjs');writeFileSync(file,`#!/usr/bin/env node\nimport { writeFileSync } from 'node:fs';\nimport path from 'node:path';\nconst args=process.argv.slice(2),i=args.indexOf('--model'),model=i>=0?args[i+1]:'';\nif(process.env.FAKE_MODE==='unavailable-luna'&&model==='gpt-5.6-luna'){console.error('unknown model gpt-5.6-luna');process.exit(5);}\nif(process.env.FAKE_MODE==='ordinary-failure'){console.error('tests failed normally');process.exit(7);}\nif(process.env.FAKE_MODE==='state-db-error'){console.error('failed to initialize sqlite state runtime at ~/.codex/state_5.sqlite: permission denied');process.exit(9);}\nif(process.env.FAKE_MODE==='require-sqlite-home'&&!String(process.env.CODEX_SQLITE_HOME||'').endsWith('/.codex/sqlite')){console.error('CODEX_SQLITE_HOME not propagated');process.exit(8);}\nif(process.env.FAKE_MODE==='mutate-production')writeFileSync(path.join(process.cwd(),'app.txt'),'worker changed\\n');\nif(process.env.FAKE_MODE==='mutate-other')writeFileSync(path.join(process.cwd(),'other.txt'),'worker changed\\n');\nconsole.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'STATUS: COMPLETED\\nCHANGED: fake\\nVALIDATED: fake\\nESCALATION: none',model},usage:{input_tokens:100,cached_input_tokens:20,output_tokens:10}}));\n`);chmodSync(file,0o755);return file;}
function workerOrder(root,{models=['gpt-5.6-luna','gpt-5.6-terra'],mutationAuthority='specrail-state-only',allowedFiles=[],protectedFiles=[]}={}){const base={schemaVersion:3,id:'WO-ABCDEF123456',taskId:'TASK-0001',phase:mutationAuthority==='production-with-scope'?'builder':'qa-engineer',actor:mutationAuthority==='production-with-scope'?'ai-flow-builder':'ai-flow-qa-engineer',action:'continue',recommendedSkill:mutationAuthority==='production-with-scope'?'ai-flow-builder':'ai-flow-qa-engineer',kind:mutationAuthority==='production-with-scope'?'implementation':'verification',requestedModels:models,reasoningEffort:'low',maxRuntimeMs:90_000,access:'workspace-write',mutationAuthority,cwd:root,request:{digest:'request-digest',text:'Validate the requested behavior.'},authority:{specificationHash:null,qaMissionHash:null,scopeGuardHash:null,decisions:''},capsule:{goal:'validate',scope:'',outOfScope:'',acceptanceCriteria:'',allowedFiles,protectedFiles,contextFiles:[],contextSymbols:[],stopIf:['material decision']},sourceDigest:'source',createdAt:new Date(0).toISOString()};const order={...base,orderDigest:digest(base)},file=path.join(root,'order.json');writeFileSync(file,`${JSON.stringify(order,null,2)}\n`);return file;}
function run(root,mode,options={},extraEnv={}){const order=workerOrder(root,options),fake=fakeCodex(root),processResult=spawnSync(process.execPath,['scripts/specrail-worker.mjs','--order',order,'--host','codex'],{cwd:process.cwd(),encoding:'utf8',env:{...process.env,...extraEnv,SPEC_RAIL_CODEX_BIN:fake,FAKE_MODE:mode||''}});let payload=null;try{payload=JSON.parse(processResult.stdout);}catch{}return{process:processResult,payload,order};}

test('state-only worker ignores unchanged pre-existing dirty production files',()=>{const root=repo();writeFileSync(path.join(root,'app.txt'),'already dirty\n');const r=run(root,'');assert.equal(r.process.status,0,r.process.stderr);assert.deepEqual(r.payload.result.changedFiles,[]);assert.deepEqual(r.payload.result.forbiddenProductionChanges,[]);});

test('state-only mutation is attributed to app.txt',()=>{const r=run(repo(),'mutate-production');assert.ok(r.payload,`stdout=${r.process.stdout}\nstderr=${r.process.stderr}`);assert.ok(r.payload.result.changedFiles.includes('app.txt'),JSON.stringify(r.payload.result,null,2));});
test('state-only mutation is classified as forbidden production',()=>{const r=run(repo(),'mutate-production');assert.deepEqual(r.payload.result.forbiddenProductionChanges,['app.txt'],JSON.stringify(r.payload.result,null,2));});
test('state-only mutation makes Worker result failed',()=>{const r=run(repo(),'mutate-production');assert.equal(r.payload.result.status,'failed',JSON.stringify(r.payload.result,null,2));assert.match(r.payload.result.summary,/WORKER_MUTATION_AUTHORITY_VIOLATION/);});
test('state-only mutation exits with governance failure code',()=>{const r=run(repo(),'mutate-production');assert.equal(r.process.status,2,`stdout=${r.process.stdout}\nstderr=${r.process.stderr}`);});

test('Builder allowed-file mutation is attributed to app.txt',()=>{const r=run(repo(),'mutate-production',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.ok(r.payload.result.changedFiles.includes('app.txt'),JSON.stringify(r.payload.result,null,2));});
test('Builder allowed-file mutation has no scope violation',()=>{const r=run(repo(),'mutate-production',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.deepEqual(r.payload.result.unexpectedScopeChanges,[],JSON.stringify(r.payload.result,null,2));assert.equal(r.process.status,0,`stdout=${r.process.stdout}\nstderr=${r.process.stderr}`);});
test('Builder outside-file mutation is attributed to other.txt',()=>{const r=run(repo(),'mutate-other',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.ok(r.payload.result.changedFiles.includes('other.txt'),JSON.stringify(r.payload.result,null,2));});
test('Builder outside-file mutation is classified as unexpected scope',()=>{const r=run(repo(),'mutate-other',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.deepEqual(r.payload.result.unexpectedScopeChanges,['other.txt'],JSON.stringify(r.payload.result,null,2));});
test('Builder outside-file mutation fails with governance exit code',()=>{const r=run(repo(),'mutate-other',{mutationAuthority:'production-with-scope',allowedFiles:['app.txt']});assert.equal(r.payload.result.status,'failed',JSON.stringify(r.payload.result,null,2));assert.equal(r.process.status,2,`stdout=${r.process.stdout}\nstderr=${r.process.stderr}`);});

test('worker falls back Luna to Terra only when Luna is unavailable',()=>{const r=run(repo(),'unavailable-luna');assert.equal(r.process.status,0,r.process.stderr);assert.deepEqual(r.payload.result.attempts.map(x=>x.model),['gpt-5.6-luna','gpt-5.6-terra']);assert.equal(r.payload.result.requestedModel,'gpt-5.6-terra');assert.equal(r.payload.result.brainModelFallbackUsed,false);});

test('ordinary Luna failure does not retry Terra or Brain',()=>{const r=run(repo(),'ordinary-failure');assert.equal(r.process.status,7);assert.deepEqual(r.payload.result.attempts.map(x=>x.model),['gpt-5.6-luna']);assert.equal(r.payload.result.brainModelFallbackUsed,false);});

test('Codex state database failure is classified as environment blocked and never retries Terra',()=>{const r=run(repo(),'state-db-error');assert.equal(r.process.status,4);assert.equal(r.payload.result.status,'environment_blocked');assert.deepEqual(r.payload.result.attempts.map(x=>x.model),['gpt-5.6-luna']);assert.match(r.payload.result.summary,/WORKER_ENVIRONMENT_BLOCKED/);});

test('Codex child inherits Desktop sqlite home when app-managed state_5 exists',()=>{const root=repo(),home=mkdtempSync(path.join(tmpdir(),'specrail-codex-home-')),sqlite=path.join(home,'.codex','sqlite');mkdirSync(sqlite,{recursive:true});writeFileSync(path.join(sqlite,'state_5.sqlite'),'test');const r=run(root,'require-sqlite-home',{}, {HOME:home,CODEX_HOME:path.join(home,'.codex'),CODEX_SQLITE_HOME:''});assert.equal(r.process.status,0,`stdout=${r.process.stdout}\nstderr=${r.process.stderr}`);});

test('identical completed WorkerOrder reuses validated result instead of spawning again',()=>{const root=repo(),first=run(root,'');assert.equal(first.process.status,0,first.process.stderr);assert.equal(first.payload.cached,false);const second=run(root,'ordinary-failure');assert.equal(second.process.status,0,`stdout=${second.process.stdout}\nstderr=${second.process.stderr}`);assert.equal(second.payload.cached,true);assert.equal(second.payload.result.status,'completed');});

test('fresh WorkerOrder lock prevents a duplicate same-phase child process',()=>{const root=repo(),orderFile=workerOrder(root),order=JSON.parse(readFileSync(orderFile,'utf8')),lockFile=path.join(root,`${order.id}.running.json`),fake=fakeCodex(root);writeFileSync(lockFile,`${JSON.stringify({schemaVersion:1,orderId:order.id,orderDigest:order.orderDigest,pid:99999,startedAt:new Date().toISOString(),staleAfterMs:120000})}\n`);const result=spawnSync(process.execPath,['scripts/specrail-worker.mjs','--order',orderFile,'--host','codex'],{cwd:process.cwd(),encoding:'utf8',env:{...process.env,SPEC_RAIL_CODEX_BIN:fake,FAKE_MODE:'ordinary-failure'}});assert.equal(result.status,6,`stdout=${result.stdout}\nstderr=${result.stderr}`);const payload=JSON.parse(result.stdout);assert.equal(payload.inFlight,true);assert.equal(payload.orderId,order.id);});

test('Brain-side loader validates result binding/model attestation and converts usage safely',()=>{const r=run(repo(),'');assert.equal(r.process.status,0,r.process.stderr);const loaded=loadWorkerResult(r.payload.resultFile,r.order);assert.equal(loaded.result.status,'completed');assert.equal(loaded.result.effectiveModel,'gpt-5.6-luna');assert.equal(loaded.result.modelAttested,true);const usage=workerUsageRecord(loaded.result,loaded.order);assert.equal(usage.owner,'worker');assert.equal(usage.model,'gpt-5.6-luna');assert.equal(usage.modelAttested,true);assert.equal(usage.inputTokens,100);assert.equal(usage.cachedInputTokens,20);assert.equal(usage.outputTokens,10);});
