#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

function parse(argv){const p=[],f={};for(let i=0;i<argv.length;i++){const v=argv[i];if(v?.startsWith('--')){const k=v.slice(2),n=argv[i+1];if(!n||n.startsWith('--'))f[k]=true;else{f[k]=n;i++;}}else if(v)p.push(v);}return{p,f};}
function stable(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;}
function digest(value){return createHash('sha256').update(stable(value)).digest('hex');}
function orderPayload(order){const {orderDigest:_ignored,...rest}=order;return rest;}
function fail(message,code=1){process.stderr.write(`${message}\n`);process.exit(code);}
function jsonLines(text){return String(text||'').split(/\r?\n/).map(line=>{try{return JSON.parse(line);}catch{return null;}}).filter(Boolean);}
function deepValues(value,key,out=[]){if(!value||typeof value!=='object')return out;if(!Array.isArray(value)&&Object.prototype.hasOwnProperty.call(value,key))out.push(value[key]);for(const item of Array.isArray(value)?value:Object.values(value))deepValues(item,key,out);return out;}
function finalText(events){for(let i=events.length-1;i>=0;i--){const e=events[i];if(e?.type==='message_end'&&e.message?.role==='assistant'){const content=e.message.content;if(typeof content==='string')return content;if(Array.isArray(content)){const text=content.filter(x=>x&&typeof x==='object'&&x.type==='text').map(x=>x.text||'').join('\n').trim();if(text)return text;}}if(e?.type==='item.completed'&&e.item?.type==='agent_message'&&typeof e.item.text==='string')return e.item.text;}return'';}
function piUsage(events){const totals={inputTokens:0,cachedInputTokens:0,outputTokens:0,cost:0};let effectiveModel=null;for(const e of events){if(e?.type!=='message_end'||e.message?.role!=='assistant')continue;const u=e.message.usage||{};totals.inputTokens+=Number(u.input||0);totals.cachedInputTokens+=Number(u.cacheRead||0);totals.outputTokens+=Number(u.output||0);totals.cost+=Number(u.cost?.total||0);if(e.message.model)effectiveModel=String(e.message.model);}return{...totals,effectiveModel};}
function codexUsage(events){let inputTokens=0,cachedInputTokens=0,outputTokens=0;for(const e of events){const usage=e?.usage||e?.turn?.usage||e?.item?.usage;if(!usage||typeof usage!=='object')continue;inputTokens=Math.max(inputTokens,Number(usage.input_tokens??usage.inputTokens??0));cachedInputTokens=Math.max(cachedInputTokens,Number(usage.cached_input_tokens??usage.cachedInputTokens??0));outputTokens=Math.max(outputTokens,Number(usage.output_tokens??usage.outputTokens??0));}return{inputTokens,cachedInputTokens,outputTokens};}
function gitFiles(cwd){const r=spawnSync('git',['status','--porcelain'],{cwd,encoding:'utf8'});if(r.status!==0)return[];return String(r.stdout||'').split(/\r?\n/).filter(Boolean).map(line=>line.slice(3).trim()).filter(Boolean).sort();}
function unavailable(text){return /unknown model|model .*not found|model .*unavailable|not available.*model|unsupported model|does not support.*model/i.test(String(text||''));}
function prompt(order){return `You are a SpecRail WORKER subagent running in an isolated process. The user-facing Brain model retains all governed decision authority.\n\nWorker order: ${order.id}\nTask: ${order.taskId}\nPhase: ${order.phase}\nKind: ${order.kind}\nSpecialist: ${order.recommendedSkill||'none'}\n\nGOAL\n${order.capsule.goal||'(none)'}\n\nSCOPE\n${order.capsule.scope||'(none)'}\n\nOUT OF SCOPE\n${order.capsule.outOfScope||'(none)'}\n\nACCEPTANCE CRITERIA\n${order.capsule.acceptanceCriteria||'(none)'}\n\nSEALED DECISIONS\n${order.authority.decisions||'(none)'}\n\nALLOWED FILES\n${order.capsule.allowedFiles.join('\n')||'(not yet sealed; remain read-only unless the assigned phase explicitly establishes scope)'}\n\nPROTECTED FILES\n${order.capsule.protectedFiles.join('\n')||'(none)'}\n\nCONTEXT SEEDS\nFiles: ${order.capsule.contextFiles.join(', ')||'none'}\nSymbols: ${order.capsule.contextSymbols.join(', ')||'none'}\n\nSTOP / ESCALATE TO BRAIN IF\n${order.capsule.stopIf.map(x=>`- ${x}`).join('\n')}\n\nRULES\n- Do not spawn another worker or subagent.\n- Do not ask the user questions from this subprocess.\n- Do not change product intent, architecture, public contracts, security/privacy policy, migration strategy, or governed UX direction.\n- You may reason locally about implementation details inside the sealed authority.\n- Use deterministic repository/tools evidence before broad reading.\n- Keep your final response compact: STATUS, CHANGED, VALIDATED, ESCALATION.\n- If a governed decision is required, output STATUS: ESCALATE_TO_BRAIN and the smallest evidence-backed decision capsule; do not guess.\n\nExecute the assigned SpecRail phase/work now.`;}
function runModel(host,model,order){const cwd=path.resolve(order.cwd);const env={...process.env,SPEC_RAIL_WORKER:'1',SPEC_RAIL_WORKER_ORDER:order.id,SPEC_RAIL_WORKER_MODEL:model};let command,args;
  if(host==='pi'){
    command=process.env.SPEC_RAIL_PI_BIN||'pi';
    args=['--mode','json','-p','--no-session','--model',model,'--thinking',order.reasoningEffort];
    if(order.access==='read-only')args.push('--tools','read,grep,find,ls,bash');
    args.push(prompt(order));
  }else if(host==='codex'){
    command=process.env.SPEC_RAIL_CODEX_BIN||process.env.CODEX_CLI_PATH||'codex';
    args=['exec','--model',model,'--json','--ephemeral','--skip-git-repo-check','-C',cwd,'--sandbox',order.access==='workspace-write'?'workspace-write':'read-only','-c',`model_reasoning_effort="${order.reasoningEffort}"`,prompt(order)];
  }else throw new Error(`Unsupported worker host: ${host}`);
  const before=gitFiles(cwd);const started=Date.now();const r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:32*1024*1024});const events=jsonLines(r.stdout);const text=finalText(events)||String(r.stdout||'').trim();const after=gitFiles(cwd);const stderr=String(r.stderr||'');
  const pi=host==='pi'?piUsage(events):null;const codex=host==='codex'?codexUsage(events):null;const effectiveModel=pi?.effectiveModel||deepValues(events,'model').map(String).find(v=>v===model)||null;
  const attestation=effectiveModel===model?'message-metadata':'command-line-explicit';
  return{code:r.status??1,signal:r.signal||null,stdout:String(r.stdout||''),stderr,text,events,requestedModel:model,effectiveModel:effectiveModel||model,attestation,usage:host==='pi'?{inputTokens:pi.inputTokens,cachedInputTokens:pi.cachedInputTokens,outputTokens:pi.outputTokens,cost:pi.cost}:{...codex,cost:null},changedFiles:[...new Set([...before,...after])].sort(),elapsedMs:Date.now()-started};
}

const {f}=parse(process.argv.slice(2));const orderFile=String(f.order||'');if(!orderFile)fail('Usage: specrail-worker --order <worker-order.json> --host codex|pi');if(!existsSync(path.resolve(orderFile)))fail(`Worker order not found: ${orderFile}`);const host=String(f.host||process.env.SPEC_RAIL_HOST||'').toLowerCase();if(!['codex','pi'].includes(host))fail('Worker host must be codex or pi');
let order;try{order=JSON.parse(readFileSync(path.resolve(orderFile),'utf8'));if(order.schemaVersion!==1||order.orderDigest!==digest(orderPayload(order)))throw new Error('worker-order integrity check failed');if(!Array.isArray(order.requestedModels)||!order.requestedModels.length)throw new Error('worker order has no model candidates');}catch(error){fail(error instanceof Error?error.message:String(error));}
let run=null;const attempts=[];for(const model of order.requestedModels){run=runModel(host,String(model),order);attempts.push({model:String(model),code:run.code,attestation:run.attestation,effectiveModel:run.effectiveModel,stderr:run.stderr.slice(0,1200)});if(run.code===0)break;if(!unavailable(`${run.stderr}\n${run.stdout}`))break;}
const resultBase={schemaVersion:1,orderId:order.id,taskId:order.taskId,host,status:run?.code===0?(run.text.includes('STATUS: ESCALATE_TO_BRAIN')?'escalated':'completed'):'failed',requestedModel:run?.requestedModel||null,effectiveModel:run?.effectiveModel||null,modelAttestation:run?.attestation||'none',brainModelFallbackUsed:false,usage:run?.usage||null,changedFiles:run?.changedFiles||[],summary:run?.text||'',attempts,startedFromOrderDigest:order.orderDigest,completedAt:new Date().toISOString(),elapsedMs:run?.elapsedMs??null};const result={...resultBase,resultDigest:digest(resultBase)};const resultFile=path.join(path.dirname(path.resolve(orderFile)),`${order.id}.result.json`);writeFileSync(resultFile,`${JSON.stringify(result,null,2)}\n`);process.stdout.write(`${JSON.stringify({resultFile,result},null,2)}\n`);if(run?.code!==0)process.exit(run?.code||1);
