#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';

function parse(argv){const p=[],f={};for(let i=0;i<argv.length;i++){const v=argv[i];if(v?.startsWith('--')){const k=v.slice(2),n=argv[i+1];if(!n||n.startsWith('--'))f[k]=true;else{f[k]=n;i++;}}else if(v)p.push(v);}return{p,f};}
function stable(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;}
function digest(value){return createHash('sha256').update(stable(value)).digest('hex');}
function orderPayload(order){const {orderDigest:_ignored,...rest}=order;return rest;}
function fail(message,code=1){process.stderr.write(`${message}\n`);process.exit(code);}
function jsonLines(text){return String(text||'').split(/\r?\n/).map(line=>{try{return JSON.parse(line);}catch{return null;}}).filter(Boolean);}
function deepValues(value,key,out=[]){if(!value||typeof value!=='object')return out;if(!Array.isArray(value)&&Object.prototype.hasOwnProperty.call(value,key))out.push(value[key]);for(const item of Array.isArray(value)?value:Object.values(value))deepValues(item,key,out);return out;}
function finalText(events){for(let i=events.length-1;i>=0;i--){const e=events[i];if(e?.type==='message_end'&&e.message?.role==='assistant'){const content=e.message.content;if(typeof content==='string')return content;if(Array.isArray(content)){const text=content.filter(x=>x&&typeof x==='object'&&x.type==='text').map(x=>x.text||'').join('\n').trim();if(text)return text;}}if(e?.type==='item.completed'&&e.item?.type==='agent_message'&&typeof e.item.text==='string')return e.item.text;}return'';}
function piUsage(events){const totals={inputTokens:0,cachedInputTokens:0,outputTokens:0,cost:0};let effectiveModel=null;for(const e of events){if(e?.type!=='message_end'||e.message?.role!=='assistant')continue;const u=e.message.usage||{};totals.inputTokens+=Number(u.input||0);totals.cachedInputTokens+=Number(u.cacheRead||0);totals.outputTokens+=Number(u.output||0);totals.cost+=Number(u.cost?.total||0);if(e.message.model)effectiveModel=String(e.message.model);}return{...totals,effectiveModel};}
function codexUsage(events){let inputTokens=0,cachedInputTokens=0,outputTokens=0;for(const e of events){const usage=e?.usage||e?.turn?.usage||e?.item?.usage;if(!usage||typeof usage!=='object')continue;inputTokens=Math.max(inputTokens,Number(usage.input_tokens??usage.inputTokens??0));cachedInputTokens=Math.max(cachedInputTokens,Number(usage.cached_input_tokens??usage.cachedInputTokens??0));outputTokens=Math.max(outputTokens,Number(usage.output_tokens??usage.outputTokens??0));}return{inputTokens,cachedInputTokens,outputTokens};}
function gitFiles(cwd){const r=spawnSync('git',['status','--porcelain','--untracked-files=all'],{cwd,encoding:'utf8'});if(r.status!==0)return[];return String(r.stdout||'').split(/\r?\n/).filter(Boolean).map(line=>line.slice(3).replace(/^"|"$/g,'').trim()).filter(Boolean).sort();}
function productionFiles(files){return files.filter(file=>!file.startsWith('.ai/')&&!file.startsWith('.codegraph/')&&!file.startsWith('.ai-flow-worktrees/'));}
function unavailable(text){return /unknown model|model .*not found|model .*unavailable|not available.*model|unsupported model|does not support.*model/i.test(String(text||''));}
function prompt(order){return `You are a SpecRail WORKER running in an isolated cheaper-model process. The user-facing Brain model retains all governed decision authority.\n\nWorker order: ${order.id}\nTask: ${order.taskId}\nPhase: ${order.phase}\nKind: ${order.kind}\nSpecialist: ${order.recommendedSkill||'none'}\nMutation authority: ${order.mutationAuthority}\n\nGOAL\n${order.capsule.goal||'(none)'}\n\nSCOPE\n${order.capsule.scope||'(none)'}\n\nOUT OF SCOPE\n${order.capsule.outOfScope||'(none)'}\n\nACCEPTANCE CRITERIA\n${order.capsule.acceptanceCriteria||'(none)'}\n\nSEALED DECISIONS\n${order.authority.decisions||'(none)'}\n\nALLOWED FILES\n${order.capsule.allowedFiles.join('\n')||'(none sealed yet)'}\n\nPROTECTED FILES\n${order.capsule.protectedFiles.join('\n')||'(none)'}\n\nCONTEXT SEEDS\nFiles: ${order.capsule.contextFiles.join(', ')||'none'}\nSymbols: ${order.capsule.contextSymbols.join(', ')||'none'}\n\nSTOP / ESCALATE TO BRAIN IF\n${order.capsule.stopIf.map(x=>`- ${x}`).join('\n')}\n\nRULES\n- Do not spawn another worker/subagent and do not ask the user questions from this process.\n- Never change product intent, architecture, public contracts, security/privacy policy, migration strategy, or governed UX direction.\n- You may reason locally about implementation details inside sealed authority.\n- If mutationAuthority is specrail-state-only, you may update SpecRail .ai state/evidence needed by the assigned role but MUST NOT change production/repository code.\n- If mutationAuthority is production-with-scope, production changes must remain strictly inside ALLOWED FILES and outside PROTECTED FILES.\n- Use deterministic repository/tool evidence before broad reading.\n- Follow the packaged specialist contract if available, but WorkerOrder authority wins over generic prose.\n- Keep final output compact: STATUS, CHANGED, VALIDATED, ESCALATION.\n- If a governed decision is required, output STATUS: ESCALATE_TO_BRAIN plus the smallest evidence-backed decision capsule. Do not guess.\n\nExecute the assigned work now.`;}
function runModel(host,model,order){const cwd=path.resolve(order.cwd);const env={...process.env,SPEC_RAIL_WORKER:'1',SPEC_RAIL_WORKER_ORDER:order.id,SPEC_RAIL_WORKER_MODEL:model};let command,args;
  if(host==='pi'){
    command=process.env.SPEC_RAIL_PI_BIN||'pi';
    args=['--mode','json','-p','--no-session','--model',model,'--thinking',order.reasoningEffort,prompt(order)];
  }else if(host==='codex'){
    command=process.env.SPEC_RAIL_CODEX_BIN||process.env.CODEX_CLI_PATH||'codex';
    args=['exec','--model',model,'--json','--ephemeral','--skip-git-repo-check','-C',cwd,'--sandbox','workspace-write','-c',`model_reasoning_effort="${order.reasoningEffort}"`,prompt(order)];
  }else throw new Error(`Unsupported worker host: ${host}`);
  const before=gitFiles(cwd);const started=Date.now();const r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:32*1024*1024});const events=jsonLines(r.stdout);const text=finalText(events)||String(r.stdout||'').trim();const after=gitFiles(cwd);const stderr=String(r.stderr||'');
  const pi=host==='pi'?piUsage(events):null;const codex=host==='codex'?codexUsage(events):null;const exact=pi?.effectiveModel||deepValues(events,'model').map(String).find(v=>v===model)||null;
  const attestation=exact===model?'runtime-metadata':'explicit-process-model';
  const changedFiles=[...new Set([...before,...after])].sort();
  return{code:r.status??1,signal:r.signal||null,stdout:String(r.stdout||''),stderr,text,events,requestedModel:model,effectiveModel:exact||model,attestation,usage:host==='pi'?{inputTokens:pi.inputTokens,cachedInputTokens:pi.cachedInputTokens,outputTokens:pi.outputTokens,cost:pi.cost}:{...codex,cost:null},changedFiles,elapsedMs:Date.now()-started};
}
async function orderFromFlags(f){if(f.order)return path.resolve(String(f.order));const task=String(f.task||'').trim();if(!task)fail('Use --order <worker-order.json> or --task TASK --actor ACTOR --action ACTION [--skill SKILL]');const root=path.resolve(String(f.root||process.cwd()));const scriptDir=path.dirname(fileURLToPath(import.meta.url));const moduleFile=path.resolve(scriptDir,'../dist/src/lib/worker-orders.js');if(!existsSync(moduleFile))fail('Compiled worker-order runtime is missing. Run SpecRail build/prepare before launching workers.');const mod=await import(pathToFileURL(moduleFile).href);const created=mod.ensureWorkerOrder(root,task,{actor:String(f.actor||''),action:String(f.action||'continue'),recommendedSkill:f.skill?String(f.skill):null});if(!created)fail('The routed step is Brain/none-owned and cannot be launched as a worker.');return created.path;}

const {f}=parse(process.argv.slice(2));const orderFile=await orderFromFlags(f);if(!existsSync(orderFile))fail(`Worker order not found: ${orderFile}`);const host=String(f.host||process.env.SPEC_RAIL_HOST||'').toLowerCase();if(!['codex','pi'].includes(host))fail('Worker host must be codex or pi');
let order;try{order=JSON.parse(readFileSync(orderFile,'utf8'));if(order.schemaVersion!==2||order.orderDigest!==digest(orderPayload(order)))throw new Error('worker-order integrity check failed');if(!Array.isArray(order.requestedModels)||!order.requestedModels.length)throw new Error('worker order has no model candidates');}catch(error){fail(error instanceof Error?error.message:String(error));}
let run=null;const attempts=[];for(const model of order.requestedModels){run=runModel(host,String(model),order);attempts.push({model:String(model),code:run.code,attestation:run.attestation,effectiveModel:run.effectiveModel,stderr:run.stderr.slice(0,1200)});if(run.code===0)break;if(!unavailable(`${run.stderr}\n${run.stdout}`))break;}
const forbiddenProduction=order.mutationAuthority==='specrail-state-only'?productionFiles(run?.changedFiles||[]):[];let status=run?.code===0?(run.text.includes('STATUS: ESCALATE_TO_BRAIN')?'escalated':'completed'):'failed';if(forbiddenProduction.length)status='failed';
const resultBase={schemaVersion:2,transport:'isolated-process',orderId:order.id,taskId:order.taskId,host,status,requestedModel:run?.requestedModel||null,effectiveModel:run?.effectiveModel||null,modelAttestation:run?.attestation||'none',modelAttested:Boolean(run?.requestedModel&&run?.effectiveModel===run?.requestedModel),brainModelFallbackUsed:false,usage:run?.usage||null,changedFiles:run?.changedFiles||[],forbiddenProductionChanges:forbiddenProduction,summary:forbiddenProduction.length?`WORKER_MUTATION_AUTHORITY_VIOLATION: ${forbiddenProduction.join(', ')}\n${run?.text||''}`:run?.text||'',attempts,startedFromOrderDigest:order.orderDigest,completedAt:new Date().toISOString(),elapsedMs:run?.elapsedMs??null};const result={...resultBase,resultDigest:digest(resultBase)};const resultFile=path.join(path.dirname(orderFile),`${order.id}.result.json`);writeFileSync(resultFile,`${JSON.stringify(result,null,2)}\n`);process.stdout.write(`${JSON.stringify({resultFile,result},null,2)}\n`);if(status==='failed')process.exit(run?.code&&run.code!==0?run.code:2);
